### PR TITLE
Added synthetics

### PR DESCRIPTION
**Pull request by kidk**
Added the multiple types of synthetic checks with link to the docs. We currently don't have a way to support this in the installation plan.

### CODE REVIEW

**Comment by jpvajda** [comment]
@polfliet @kidk what is this PR in relation to?

**Review by jpvajda — CHANGES_REQUESTED** [review]
Just want to understand what this for, as I thought sythetics is out of scope for GA. cc @aswanson-nr for visibility.

**Comment by polfliet** [comment]
@jpvajda Sam is working through the Add more data sources and adding those as documentation packs for now.
As we discussed, and as listed out in this sheet https://docs.google.com/spreadsheets/d/1jMsQAjXSsK8DEmWXqKmW5bw-Vq3BsvUKn2hnaxz5IdE/edit#gid=0

**Review by polfliet — APPROVED** [review]

**Comment by jpvajda** [comment]
@polfliet sure no worries. I was just considering if we 

`1` need to add any PR checks to support the additions of synthetics soon 
`2` If we should document that these are not fully supported yet, and contributors shouldn't be added them to quickstarts at this time.

**Comment by jpvajda** [comment]
@kidk it does. so it will follow the same logic we have today for showing `see docs` button OR showing the `install` button.

**Comment by kidk** [comment]
Correct 👍

**Pull request merged**
