### PR TITLE
Added notice on OHI's that we will install New Relic Infra

### PR DESCRIPTION
**Pull request by kidk**
We removed the infra step so users won't know we need to install New Relic Infra. This adds a notice in the UI that we will add it. 

Before we merge this I do have a couple of questions.

### CODE REVIEW

**Comment by kidk** [comment]
@jbeveland27 Do you know if we can use Markdown in the description?

**Comment by jbeveland27** [comment]
@kidk From an API standpoint, markdown will work fine. However the UI isn't doing anything to parse and render markdown for the `description` field at the moment (from what I know), so that'd have to be added

**Comment by kidk** [comment]
Thanks @jbeveland27 Let's leave it as is for now, and improve after launch.

**Review by jbeveland27 — APPROVED** [review]

**Comment by jbeveland27** [comment]
@kidk I'll merge and redeploy the service to pull these changes in. I think you might want to double check to see if the content lines up the way you'd expect. I don't think the newlines will actually translate to anything, so will have to see how it renders.

**Pull request merged**
