### PR TITLE
Added xamarin instructions in the packs

### PR DESCRIPTION
**Pull request by vvydier**
## Summary

This pack has directions on how to use  Xamarin bindings with the Newrelic's Mobile SDK

### Screenshots

The metrics and traces from Xamarin app show up in Newrelic's Mobile APM screen

### CODE REVIEW

**Review by polfliet — CHANGES_REQUESTED** [review]
Hey @vvydier I can only see an empty readme file? Did you forget to commit the file?

**Comment by vvydier** [comment]
Hi @polfliet,

Can you check and see if you can see it now. Not sure what happened last time.

Thanks
-Vinod

**Comment by polfliet** [comment]
Hey @vvydier, I can see the file, but this is not the format we are expecting.

Please have a look at [this other example](https://github.com/newrelic/newrelic-observability-packs/tree/main/packs/ibmmq) from New Relic Labs.
The idea is to create a config file, and then refer in that config file to the readme you should host in the project's github repository.

Here is some more info:
* [Example template](https://github.com/newrelic/newrelic-observability-packs/tree/main/_template)
* [Contributing guidelines](https://github.com/newrelic/newrelic-observability-packs/blob/main/CONTRIBUTING.md)
Let me know if you have questions!

**Comment by vvydier** [comment]
@polfliet I have added a config.yml and png's for the xamarin pack. Thanks

**Comment by vvydier** [comment]
@polfliet deleted README.md and updated metadata according to the format requested

**Comment by vvydier** [comment]
Hi @polfliet, All checks have passed, should be good now? Thanks

**Review by polfliet — APPROVED** [review]

**Pull request merged**
