### PR TITLE
feat(import-data): Added deprecation notice

### PR DESCRIPTION
**Pull request by kidk**
Added deprecation notice to the import CLI so it's clear user should not be using this in production environments.

I also ran the linter so there were so style changes.

### CODE REVIEW

**Comment by jbeveland27** [comment]
I wonder if we should say something like "warning: the importer is only for testing packs and not meant to be used in a production environment". Calling it deprecated feels heavy handed to me since it's still a utility we plan to use for PR validations (unless that's changed)

**Comment by kidk** [comment]
Thanks @jbeveland27 I've made the changes, and wording review by @polfliet

**Review by polfliet — APPROVED** [review]

**Comment by polfliet** [comment]
@jbeveland27 you ok with this PR?

**Comment by jbeveland27** [comment]
@polfliet Ah sorry missed the update. Yep, good to go! :shipit:

**Review by jbeveland27 — APPROVED** [review]

**Pull request merged**
