### PR TITLE
chore: update contributor guide

### PR DESCRIPTION
**Pull request by jpvajda**
This PR gives a contributor some guidelines to consider as the work to submit a new pack or review a PR on an existing pack. It's dependent on our conversation around limitations for the API

### CODE REVIEW

**Comment by jpvajda** [comment]
@kidk FYI

**Comment by jpvajda** [comment]
IS blocked by this https://github.com/newrelic/newrelic-observability-packs/issues/53 until we finalize these specifications.

**Comment by jpvajda** [comment]
still blocked but i've followed up with @kidk and @jbeveland27 on #53 so we can confirm our approach, then I can update this PR

**Comment by jpvajda** [comment]
waiting on the final api limits , repo limits etc to make this PR more concise

**Comment by jpvajda** [comment]
removed details on pack limits and checks until we define those in the next sprint.

**Review by nr-kkenney — APPROVED** [review]

**Comment by jpvajda** [comment]
This PR will be followed up with updates  after we kick off our next epic focused on repo automation

**Pull request merged**
