### PR TITLE
Contributing update + remove label workflow

### PR DESCRIPTION
**Pull request by jpvajda**
This PR updates the contributing guide for clarity and md linting as well as remove the labels workflow

### CODE REVIEW

**Comment by aswanson-nr** [comment]
@jpvajda Could you remove the [script](https://github.com/newrelic/newrelic-observability-packs/blob/main/utils/check_support_level.js) and the `yarn run` command [here](https://github.com/newrelic/newrelic-observability-packs/blob/main/utils/package.json#L11)?

**Comment by jpvajda** [comment]
@aswanson-nr  done!

**Comment by aswanson-nr** [comment]
Agggh! @jpvajda I forgot about the unit tests, you'll have to remove https://github.com/newrelic/newrelic-observability-packs/blob/main/utils/__tests__/check_support_level.test.js

**Comment by jpvajda** [comment]
@aswanson-nr removed the unit tests.

**Review by aswanson-nr — APPROVED** [review]
:shipit:

**Pull request merged**
